name = "StructuralDynamicsODESolvers"
uuid = "5837384c-0389-41f0-a8dd-204a40e5dede"
authors = ["jorgepz <jorgepz@fing.edu.uy>", "mforets  <mforets@gmail.com>", "dfcaporale  <dfcaporale@gmail.com>"]
version = "0.1.1"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathematicalSystems = "d14a8603-c872-5ed3-9ece-53e0e82e39da"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
CommonSolve = "0.2"
DocStringExtensions = "0.8"
FillArrays = "0.10, 0.11"
MathematicalSystems = "0.11"
Reexport = "0.2, 1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
